config/routes.rb
Rails.application.routes.draw do
  devise_for :users, controllers: { sessions: 'users/sessions', registrations: 'users/registrations', omniauth_callbacks: 'users/omniauth_callbacks' }
  # For details on the DSL available within this file, see http://guides.rubyonrails.org/routing.html
  resources :users, only: %i[show index] do
    resources :posts, only: %i[create]
    resources :friendships, only: %i[create]
  end
  resources :posts, only: %i[create index show] do
    resources :comments, only: %i[create], controller: :post_actions
    resources :likes, only: %i[create], controller: :post_actions
  end
  resources :friendships, only: :update

  root to: 'posts#index'

  devise_scope :user do
    get 'login', to: 'devise/sessions#new'
  end
end

app/views/shared/_navbar.html.erb
<nav class="navbar navbar-light fixed" style="background-color: #73C8A9">
  <div class="container">
    <%= link_to (icon('fas', 'feather', 'Chronicle')), root_path, :class => "navbar-brand"   %>

    <div class="navbar-nav d-flex flex-row">
      <% if user_signed_in? %>
        <% if current_user.received_friend_requests.length > 0 %>
          <%= link_to icon('fas', 'bell', content_tag(:span, "#{current_user.received_friend_requests.count}", :class => "align-top badge badge-pill badge-dark")) , users_path , :class => "nav-item nav-link mr-3" %>
        <% else %>
          <%= link_to icon('fas', 'bell') , users_path , :class => "nav-item nav-link mr-3" %>
        <% end %>

        <%= link_to "Hello, #{current_user.first_name}", user_path(current_user.id), :class => "nav-item nav-link mr-3" %>
        <%= link_to "Log out", destroy_user_session_path , method: :delete, :class => "nav-item nav-link mr-3" %>

      <% else %>
        <%= link_to "Login", login_path, :class => "nav-item nav-link mr-3" %>
        <%= link_to "Sign up", new_user_registration_path, :class => "nav-item nav-link mr-3" %>

      <% end %>
    </div>
  </div>
</nav>