config/routes.rb
Rails.application.routes.draw do
  devise_for :users, controllers: { sessions: 'users/sessions', registrations: 'users/registrations', omniauth_callbacks: 'users/omniauth_callbacks' }
  # For details on the DSL available within this file, see http://guides.rubyonrails.org/routing.html
  resources :users, only: %i[show index] do
    resources :posts, only: %i[create]
    resources :friendships, only: %i[create]
  end
  resources :posts, only: %i[create index show] do
    resources :comments, only: %i[create], controller: :post_actions
    resources :likes, only: %i[create], controller: :post_actions
  end
  resources :friendships, only: :update

  root to: 'posts#index'

  devise_scope :user do
    get 'login', to: 'devise/sessions#new'
  end
end

app/models/friendship.rb
class Friendship < ApplicationRecord
  enum status: %i[requested accepted rejected]
  belongs_to :user
  belongs_to :friend,class_name: "User"
end

app/controllers/friendships_controller.rb
class FriendshipsController < ApplicationController
  def index
    users = current_user.requesters
    @slices = []
    users.each_slice((users.length/2.0).ceil){|s| @slices << s} unless users.empty?
  end

  def create
    user = User.find(params[:user_id])
    fr = Friendship.create(user: current_user, friend: user, status: :requested)
    redirect_back(fallback_location: users_path) if fr.save
  end

  def update
    fr = Friendship.find(params[:id])
    fr.status = params[:status]
    redirect_back(fallback_location: users_path) if fr.save
  end
end

app/views/friendships/_request.html.erb
<div class="d-flex align-items-center mb-3">
  <%= image_tag(user.avatar.url, class: "img-fluid mr-3", style: "width: 100px") %>
  <%= link_to "#{user.fullname}", user_path(user), class: "mr-auto" %>
  <% if !user.requesters.nil? && user.requesters.include?(current_user) %>
    <%= content_tag(:div, icon('fas','check', 'Requested')) %>
  <% elsif !user.requestees.nil? && user.requestees.include?(current_user) %>
    <%= link_to icon('fas','check', 'Accept Request'), friendship_path(current_user.get_friendship(user), status: "accepted"), class: "btn btn-primary btn-sm", method: :put %>
  <% elsif !user.friends.nil? && user.friends.include?(current_user) %>
    <%= content_tag(:div, icon('fas','user-friends', 'Friends')) %>
  <% else %>
    <%= link_to icon('fas','plus', 'Add Friend'), user_friendships_path(user), class: "btn btn-primary btn-sm", method: :post %>
  <% end %>
</div>