config/routes.rb
Rails.application.routes.draw do
  devise_for :users, controllers: { sessions: 'users/sessions', registrations: 'users/registrations', omniauth_callbacks: 'users/omniauth_callbacks' }
  # For details on the DSL available within this file, see http://guides.rubyonrails.org/routing.html
  resources :users, only: %i[show index] do
    resources :posts, only: %i[create]
    resources :friendships, only: %i[create]
  end
  resources :posts, only: %i[create index show] do
    resources :comments, only: %i[create], controller: :post_actions
    resources :likes, only: %i[create], controller: :post_actions
  end
  resources :friendships, only: :update

  root to: 'posts#index'

  devise_scope :user do
    get 'login', to: 'devise/sessions#new'
  end
end

app/models/post.rb
class Post < ApplicationRecord
  belongs_to :author, class_name: :User, foreign_key: :user_id
  has_many :likes, ->{where(action: :like)}, class_name: :PostAction
  has_many :views, ->{where(action: :view)}, class_name: :PostAction
  has_many :comments, ->{where(action: :comment)}, class_name: :PostAction
  has_many :likers, through: :likes, source: :user
  has_many :viewers, through: :views, source: :user
  has_many :commenters, through: :comments, source: :user

  def display_likers(names = likers_names)
    count = names.count

    case
    when count > 3
      "#{names.first}, #{names.second} and #{count - 2} others"
    when count == 3
      "#{names.first}, #{names.second} and #{names.third}"
    when count == 2
      "#{names.first} and #{names.second}"
    when count == 1
      names.take(1)
    end
  end

  def likers_names
    likers.map(&:fullname)
  end
end

app/models/post_action.rb
class PostAction < ApplicationRecord
  belongs_to :post
  belongs_to :user
  enum action: %i[comment like view]
  validates_presence_of :content, if: :comment?
  validates_absence_of :content, unless: :comment?
  validates_uniqueness_of :user, scope: [:post, :action], if: :like?
end

app/controllers/posts_controller.rb
class PostsController < ApplicationController
  before_action :authenticate_user!

  def index
    @posts = current_user.timeline_posts.order(created_at: :desc)
  end

  def create
    post = current_user.posts.new(:content => params[:post][:content])
    redirect_back(fallback_location: user_path(current_user)) if post.save
  end

  def show
    @post = Post.find(params[:id])
  end

  private

  def post_params
    params.require(:post).permit(:content)
  end

end

app/helpers/posts_helper.rb
module PostsHelper
  def displayLikers(post)
    n = post.likers.count
    case n
    when 1
      "#{post.likers.first.fullname}"
    when 2
      "#{post.likers.first.fullname} and #{post.likers.second.fullname}"
    when 3
      "#{post.likers.first.fullname}, #{post.likers.second.fullname} and #{post.likers.third.fullname}"
    when n > 3
      "#{post.likers.first.fullname}, #{post.likers.second.fullname} and #{n - 2} others"
    end
  end
end

app/views/posts/_new_post.html.erb
<div class="list-group post mb-3">
    <%= form_for :post, url: user_posts_path(current_user) do |f| %>
      <div class="list-group-item">
        <%= f.text_field :content, class: "form-control", placeholder: "What's on your mind?"%>
      </div>
      <div class="list-group-item d-flex justify-content-end">
        <%= f.submit "Post", class: "btn btn-primary btn-sm" %>
      </div>
    <% end %>
</div>

app/views/posts/_post.html.erb
<div class="card post mb-3">
  <div class="card-header">
    <div class="container">
      <div class="row">
        <div class="col-2">
          <%= image_tag(post.author.avatar.url, class: "img-fluid rounded-circle") %>
        </div>
        <div class="col d-flex flex-column justify-content-center">
          <%= content_tag(:div, post.author.fullname)%>
          <%= content_tag(:div, post.created_at.to_formatted_s(:long))%>
        </div>
      </div>
    </div>
  </div>
  <div class="list-group list-group-flush">
    <div class="list-group-item">
      <%= post.content %>
    </div>
    <%= form_with url: post_comments_path(post, post_action: :comment) do |form| %>
      <div class="list-group-item d-flex justify-content-between">
        <%= link_to "Like", post_likes_path(post, post_action: :like), class: "btn btn-primary", method: :post %>
        <%= form.submit "Comment", class: "btn btn-primary" %>
      </div>
      <% unless post.likes.empty? %>
       <div class="list-group-item" id="likes">
          <%= icon('fas', 'thumbs-up', post.display_likers) %>
        </div>
      <% end %>
      <% unless post.comments.empty? %>
        <div class="list-group-item">
          <%= render partial: "post_actions/comment", collection: post.comments %>
        </div>
      <% end %>
      <div class="card-footer">
        <div class="form-row">
          <div class="col">
            <%= form.text_field :content, class: "form-control", placeholder: "Add a comment..." %>
          </div>
        </div>
      </div>
    <% end %>
  </div>
</div>

app/views/posts/create.html.erb
<h1>Posts#create</h1>
<p>Find me in app/views/posts/create.html.erb</p>

app/views/posts/index.html.erb
<div class="container mt-3">
  <div class="row justify-content-center">
    <div class="col-lg-6">
      <%= render partial: "posts/new_post" %>
      <%= render @posts %>
    </div>
  </div>
</div>

app/views/posts/show.html.erb
<div class="container mt-3">
  <div class="row justify-content-center">
    <div class="col-lg-6">
      <%= render @post %>
    </div>
  </div>
</div>